version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:   ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  parser:
    build:
      context: .
      dockerfile: Dockerfile.parser
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8001:8001"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - db
      - parser
      - redis
    environment:
      DATABASE_URL:       ${DATABASE_URL}
      PARSER_SERVICE_URL: ${PARSER_SERVICE_URL}
      REDIS_URL:          ${REDIS_URL}
    ports:
      - "8000:8000"

volumes:
  db_data:
