site_name: "Средства Web-программирования"
site_url: https://Kew1710.github.io/ITMO_ICT_WebDevelopment_tools_2024-2025/
theme:
  name: material
nav:
  - "Главная": index.md
  - "Лабораторные работы":
      - "ЛР1. FastAPI": lab1.md
      - "ЛР2. Потоки и async": lab2.md
      - "ЛР3. Docker и очереди": lab3.md